version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${AUCTION_APP_PORT_DB}:5432
    environment:
      POSTGRES_USER: ${AUCTION_APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUCTION_APP_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUCTION_APP_POSTGRES_DB}
  redis:
    image: redis:6.2
    ports:
      - ${AUCTION_APP_BROKER_PORT}:6379
volumes:
  database-data: # named volumes can be managed easier using docker-compose
