# Generated by Django 3.1.7 on 2021-03-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction_app', '0001_initial'),
        ('item_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='auction_app.baseauction')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='item_app.item')),
            ],
        ),
    ]
