# Generated by Django 3.1.7 on 2021-03-18 09:23

import auction_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start auction')),
                ('end_date', models.DateTimeField(verbose_name='End auction')),
                ('current_price', auction_app.models.CurrencyField(decimal_places=2, max_digits=10, verbose_name='Current_price')),
            ],
        ),
        migrations.CreateModel(
            name='DutchAuction',
            fields=[
                ('baseauction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction_app.baseauction')),
                ('end_price', auction_app.models.CurrencyField(decimal_places=2, max_digits=10, verbose_name='End price')),
                ('update_price_frequency', models.PositiveSmallIntegerField(verbose_name='Frequency to reduce')),
            ],
            bases=('auction_app.baseauction',),
        ),
        migrations.CreateModel(
            name='EnglishAuction',
            fields=[
                ('baseauction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auction_app.baseauction')),
                ('buy_it_now_price', auction_app.models.CurrencyField(decimal_places=2, max_digits=10, verbose_name='Buy now price')),
                ('reserved_price', auction_app.models.CurrencyField(decimal_places=2, max_digits=10, verbose_name='Start price')),
            ],
            bases=('auction_app.baseauction',),
        ),
    ]
