# Generated by Django 3.1.7 on 2021-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20210319_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], default=2),
            preserve_default=False,
        ),
    ]
