# Generated by Django 3.1.7 on 2021-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_auto_20210406_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutchauction',
            name='update_price_frequency',
            field=models.PositiveSmallIntegerField(help_text='Update_price_frequency means that how mane time price will be updated', verbose_name='Frequency to reduce'),
        ),
    ]
